export const REQUEST_LIST_FRIEND = 'REQUEST_LIST_FRIEND';
export const RESPONSE_LIST_FRIEND = 'RESPONSE_LIST_FRIEND';
export const REQUEST_LIST_FRIEND_REQUEST = 'REQUEST_LIST_FRIEND_REQUEST';
export const RESPONSE_LIST_FRIEND_REQUEST = 'RESPONSE_LIST_FRIEND_REQUEST';